### PR TITLE
Improved the CSS of Sign-In/Sign-Up Form.

### PR DESCRIPTION
**Pull request by KiranAminPanjwani**
# Pull Request template
Please, go through these steps before you submit a PR.

Make sure you have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/sign-in issues or `feature/added-home button`.

# Describe your changes

- I have changed the CSS of the input field, button, and font family.
- I have designed a fully responsive login form.

### Fixes issue #243 
 -------------------------------------------------------------------------------------

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Please ensure that there aren't other open [Pull Requests](../../../pulls) for the same update/change/feature/bugs?
- [x] The title pull request is a short description of the proposed changes.

 ## Screenshots

image

image

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
@aytida0606 Kindly review and merge it. Thank you.

**Comment by aytida0606** [comment]
@KiranAminPanjwani
2217c48d-290e-4420-926c-7c5e67e78d65
 https://dribbble.com/shots/10761532-Login-Web-Animation?utm_source=Clipboard_Shot&utm_campaign=OlenaKychun&utm_content=Login%20Web%20Animation&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=OlenaKychun&utm_content=Login%20Web%20Animation&utm_medium=Social_Share

https://user-images.githubusercontent.com/73810643/170811248-d145d8a7-796b-4546-8e8a-6f1944647b0e.mp4
 use this as reference

**Comment by aytida0606** [comment]
@KiranAminPanjwani are you working on this issue ? 
31 may is last day of contribution .

**Comment by KiranAminPanjwani** [comment]
Yes, I'm trying. Will it be count as a separate contribution?

**Comment by aytida0606** [comment]
> Yes, I'm trying. Will it be count as a separate contribution?


 the sign in page should have square / box design  instead of rectangular one. ( Level 2)
The pr changes has been reverted , so it doesn't count. Add the changes and make a new pr

**Comment by KiranAminPanjwani** [comment]
Okie I am trying my best sir.

**Comment by aytida0606** [comment]
> Okie I am trying my best sir.

Just make the sign in page square / box . No need to make additional changes.

**Comment by KiranAminPanjwani** [comment]
@aytida0606 I have done it! Shall I create a new pull request?

**Comment by aytida0606** [comment]
> @aytida0606 I have done it! Shall I create a new pull request?

Yes , add screenshot .

**Pull request merged**
