### PR TITLE
Improved Navbar of website

### LINKED ISSUE #245: Improve Navbar
- **Do you want to request a *feature* or report a *bug*?**
- **Do the checklist before filing an issue:**

- [x] feature request

create a feature request
------------------------------------------------------------------
- [x] Have an idea for a feature?
- [x] Provide **screenshots** where appropriate

## Expected Behavior
I want to improve UI of navbar. Margin and padding are not so good. Also the leafy border are not looking so good.

## Screenshot

ss2

### PR DESCRIPTION
**Pull request by Areebah03**
*Fixed #245

# Pull Request template
Please, go through these steps before you submit a PR.

Make sure you have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/addded-home button`.

# Describe your changes
I have improved the navbar of entire website by adjusting margin, padding, changing fonts, improving hover effects. I have also improved navbar of different pages of website.

### Issue  number and link
#245 

 -------------------------------------------------------------------------------------

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Please ensure that there aren't other open [Pull Requests](../../../pulls) for the same update/change/feature/bugs?
- [x] The title  pull request is a short description of the proposed changes.

 ## Screenshots
ss1
ss2
ss3
ss4
ss5
ss6

### CODE REVIEW

**Comment by aytida0606** [comment]
fetch the changes @Areebah03

**Comment by Areebah03** [comment]
@aytida0606 I have solved the merge conflicts. Kindly view.

**Comment by aytida0606** [comment]
@Areebah03 its not working in index.html /home page

**Comment by Areebah03** [comment]
@aytida0606 Can I make the pull request again with all the changes? I think there was a problem will merging.

**Comment by aytida0606** [comment]
yeah sure , add underline highlight and if possible change the colour too.

**Pull request merged**
