### PR TITLE
Fixed Links in login page

### LINKED ISSUE #225: Links broken in Login page
- [x] bug report

create a bug report
------------------------------------------------------------------

- [x] Provide **screenshots** where appropriate

## Expected Behavior
Link page of respective link to respective section of page
## Current Behavior
Giving a 404 error of github, page not found

## Possible Solution
Improving links in navbar of login.html

## Steps to Reproduce

1. Go to login page
2. Click any link except home

## Context (Environment)

Not proper navigation in website due to broken links

## Detailed Description

The links are broken in login page except home page and it takes to github 404 error page

## Screenshot

image

### PR DESCRIPTION
**Pull request by aaryahjolia**
# Describe your changes
Improved links in login page to navigate easily without 404 error page

### Fixes #225 

 -------------------------------------------------------------------------------------

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Please ensure that there aren't other open [Pull Requests](../../../pulls) for the same update/change/feature/bugs?
- [x] The title  pull request is a short description of the proposed changes.

### CODE REVIEW

**Comment by aytida0606** [comment]
@aaryahjolia links are already fixed.

**Comment by aaryahjolia** [comment]
Where are they fixed ? @aytida0606 
IMG_20220513_160022

**Comment by aytida0606** [comment]
> Where are they fixed ? @aytida0606 IMG_20220513_160022

what do you want to add its already working fine there no need to change anything.

**Comment by aaryahjolia** [comment]
This error @aytida0606 

https://user-images.githubusercontent.com/82600388/168267422-bbc165cd-d5e8-4108-8f50-05949e91e555.mp4

**Comment by aytida0606** [comment]
> This error @aytida0606
> 
>  2022-05-13.16-11-34.mp4

ok i didn't merge the changes on my side

**Pull request merged**
